/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.aws_project_region,
    "aws_appsync_graphqlEndpoint": process.env.aws_appsync_graphqlEndpoint,
    "aws_appsync_region": process.env.aws_project_region,
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": process.env.aws_appsync_apiKey
};


export default awsmobile;
