/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
   
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_xvFW9UfFx",
        "userPoolWebClientId": "4ehlh48b4vgvadsmt7sgnmejt9"
    }
};


export default awsmobile;
