/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
   
    "Auth": {
        "region": "ENTER YOUR REGION",
        "userPoolId": "ENTER YOUR POOL ID",
        "userPoolWebClientId": "ENTER YOUR CLIENT ID"
    }
};


export default awsmobile;
