/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_13DPJbYqK",
        "userPoolWebClientId": "6e0tcdhqkemgkddnv943717p9e",
        "identityPoolId": "us-east-2:1a9357ed-4cbe-4306-8f9f-dead6cd0b8c7"
    },
    "Storage": {
        "AWSS3": {
            "bucket": 'example04userpoolwithidentitypool-uploads4f6eb0fd-1qy7fs6u15ob9', //Bucket Name
            "region": "us-east-2" //Bucket Region
        }
    },
    "aws_project_region": "us-east-2",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;