/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
   
    "Auth": {
        "region": "ADD YOUR REGION",
        "userPoolId": "ADD YOUR POOL ID",
        "userPoolWebClientId": "ADD YOUR CLIENT ID"
    }
};


export default awsmobile;
