/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_QuUHlv0fq",
        "userPoolWebClientId": "4mapge0u1e1ui0tkvqfep17259",
        "identityPoolId" : "us-east-2:3b55cacc-8ead-463d-8ce1-0d31cfa83e77"
    },
};


export default awsmobile;
